name: Deploy Storybook

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  yarn:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Run Yarn Install
      - name: Run Yarn Install
        run: yarn install

      # Run Npm deploy-storybook
      - name: Deploy storybook to Github Pages
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
